#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_read_indicator:
  path: /indicator/{idIndicator}/
  controller: SIMBA3\Api\Controller\Indicator\ReadIndicatorController::execute
  methods: GET
  requirements:
    idIndicator: '\d+'
