#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_read_indicator:
  path: /indicator/{indicatorId}/
  controller: SIMBA3\Api\Controller\Indicator\ReadIndicatorController::execute
  methods: GET
  requirements:
    indicatorId: '\d+'


api_read_values_indicator:
  path: /indicator/{indicatorId}/values/
  controller: SIMBA3\Api\Controller\Value\ReadValuesIndicatorController::execute
  methods: GET
  requirements:
    indicatorId: '\d+'


api_read_area_types:
  path: /area-type/
  controller: SIMBA3\Api\Controller\Area\ReadAllTypeAreaController::execute
  methods: GET


api_read_area_:
  path: /area-type/{areaTypeId}/area/
  controller: SIMBA3\Api\Controller\Area\ReadAreaTypeAreaController::execute
  methods: GET
  requirements:
    indicatorId: '\d+'