# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    SIMBA3\:
        resource: '../src/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    #App\Controller\:
    #    resource: '../src/Controller/'
    #    tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    SIMBA3\Api\Controller\Indicator\ReadIndicatorController:
        tags: [controller.service_arguments]
        arguments:
            - "@simba3.useCase.readInfoIndicator"

    SIMBA3\Api\Controller\Value\ReadValuesIndicatorController:
        tags: [controller.service_arguments]
        arguments:
            - "@simba3.useCase.readValuesIndicator"

    SIMBA3\Api\Controller\Variable\ReadAllTypeAreaController:
        tags: [controller.service_arguments]
        arguments:
            - "@simba3.useCase.ReadAllTypeArea"

    SIMBA3\Api\Controller\Variable\ReadAllAreaTypeAreaController:
        tags: [controller.service_arguments]
        arguments:
            - "@simba3.useCase.ReadAllAreaTypeArea"

    simba3.useCase.readInfoIndicator:
        class: SIMBA3\Component\Application\Indicator\UseCase\ReadInfoIndicatorUseCase
        arguments:
            - "@simba3.repository.doctrine.indicator"

    simba3.useCase.readValuesIndicator:
        class: SIMBA3\Component\Application\Value\UseCase\ReadValuesIndicatorUseCase
        arguments:
            - "@simba3.repository.doctrine.indicator"
            - "@simba3.factory.typeValue"
            - "@simba3.useCase.readDictionaryVariables"

    simba3.useCase.readDictionaryVariables:
        class: SIMBA3\Component\Application\Value\UseCase\ReadDictionaryVariablesUseCase
        arguments:
            - "@simba3.repository.doctrine.area"

    simba3.useCase.ReadAllTypeArea:
        class: SIMBA3\Component\Application\Variable\UseCase\ReadAllTypeAreaUseCase
        arguments:
            - "@simba3.repository.doctrine.typeArea"

    simba3.useCase.ReadAllAreaTypeArea:
        class: SIMBA3\Component\Application\Variable\UseCase\ReadAllAreaTypeAreaUseCase
        arguments:
            - "@simba3.repository.doctrine.typeArea"
            - "@simba3.repository.doctrine.area"

    simba3.factory.typeValue:
        class: SIMBA3\Component\Domain\Value\Service\FactoryTypeValue
        arguments:
            - "@simba3.repository.doctrine.areaYearValue"
            - "@simba3.repository.doctrine.yearValue"

    simba3.repository.doctrine.indicator:
        class: SIMBA3\Api\Persistence\Repository\Indicator\DoctrineIndicatorRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@simba3.repository.metadata.indicator"

    simba3.repository.doctrine.areaYearValue:
        class: SIMBA3\Api\Persistence\Repository\Value\DoctrineAreaYearValueRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@simba3.repository.metadata.areaYearValue"

    simba3.repository.doctrine.yearValue:
        class: SIMBA3\Api\Persistence\Repository\Value\DoctrineYearValueRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@simba3.repository.metadata.yearValue"

    simba3.repository.doctrine.typeArea:
        class: SIMBA3\Api\Persistence\Repository\Variable\DoctrineTypeAreaRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@simba3.repository.metadata.typeArea"

    simba3.repository.doctrine.area:
        class: SIMBA3\Api\Persistence\Repository\Variable\DoctrineAreaRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@simba3.repository.metadata.area"

    simba3.repository.metadata.indicator:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - SIMBA3\Component\Domain\Indicator\Entity\Indicator

    simba3.repository.metadata.areaYearValue:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - SIMBA3\Component\Domain\Value\Entity\AreaYearValue

    simba3.repository.metadata.yearValue:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - SIMBA3\Component\Domain\Value\Entity\YearValue

    simba3.repository.metadata.typeArea:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - SIMBA3\Component\Domain\Variable\Entity\TypeArea

    simba3.repository.metadata.area:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - SIMBA3\Component\Domain\Variable\Entity\Area
