<?php

namespace SIMBA3\Component\Application\Value\Response;

use PHPUnit\Framework\TestCase;
use SIMBA3\Component\Domain\Value\Service\TypeValueArray;

class ReadValuesIndicatorResponseTest extends TestCase
{
    private ReadValuesIndicatorResponse $readValuesIndicatorResponse;
    private TypeValueArray $typeValueArray;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->typeValueArray = $this->createMock(TypeValueArray::class);
    }

    /** @test */
    public function shouldReadValuesIndicatorResponseReturnTypeValuesAsArray(): void
    {
        $this->givenAReadValuesIndicatorResponse();
        $this->givenATypeValueArray();
        $this->thenReturnAnArray();
    }


    private function givenAReadValuesIndicatorResponse(): void
    {
        $this->readValuesIndicatorResponse = new ReadValuesIndicatorResponse($this->typeValueArray);
    }

    private function givenATypeValueArray(): void
    {
        $this->typeValueArray->method("getValuesAsArray")->willReturn(
            [[33, 45, 344.5, "hello"], [3, 6, 8, 55.3, "bye"]]
        );
    }

    private function thenReturnAnArray(): void
    {
        $this->assertEquals(
            [[33, 45, 344.5, "hello"], [3, 6, 8, 55.3, "bye"]],
            $this->readValuesIndicatorResponse->getValuesAsArray()
        );
    }
}
