doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'

        dbname:     '%env(POSTGRES_DB)%'
        host:       db
        port:       5432
        user:       '%env(POSTGRES_USER)%'
        password:   '%env(POSTGRES_PASSWORD)%'
        driver:     pdo_pgsql


        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Indicator:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Api/Persistence/Migrations/Indicator'
                prefix: 'SIMBA3\Component\Domain\Indicator'
                alias: Indicator

            Value:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Api/Persistence/Migrations/Value'
                prefix: 'SIMBA3\Component\Domain\Value'
                alias: Value

            Variable:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Api/Persistence/Migrations/Variable'
                prefix: 'SIMBA3\Component\Domain\Variable'
                alias: Variable

