<?php

namespace SIMBA3\Component\Domain\Indicator\Entity;

use PHPUnit\Framework\TestCase;

class IndicatorTest extends TestCase
{
    private Indicator $indicator;
    private TypeIndicator $typeIndicator;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->typeIndicator = $this->createMock(TypeIndicator::class);
    }

    /** @test */
    public function shouldReturnIndicatorValues()
    {
        $this->givenAIndicator();
        $this->thenReturnValidInfoIndicator();
    }

    private function givenAIndicator()
    {
        $this->indicator = new Indicator(
            2,
            $this->typeIndicator
        );
    }

    private function thenReturnValidInfoIndicator()
    {
        $this->assertEquals(2, $this->indicator->getDecimals());
        $this->assertSame($this->typeIndicator, $this->indicator->getTypeIndicator());
    }
}
