<?php

namespace SIMBA3\Component\Domain\Value\Entity;

use PHPUnit\Framework\TestCase;
use SIMBA3\Component\Domain\Value\Repository\ValueRepository;

class AreaYearTypeValueTest extends TestCase
{
    private AreaYearTypeValue $areaYearTypeValue;
    private ValueRepository $valueRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->valueRepository = $this->createMock(ValueRepository::class);
    }

    /** @test */
    public function shouldAreaYearTypeValueReturnTypeValueArray(): void
    {
        $this->givenAnAreaYearTypeValue();
        $this->thenReturnTypeValueArray();
    }

    public function givenAnAreaYearTypeValue(): void
    {
        $this->areaYearTypeValue = new AreaYearTypeValue($this->valueRepository);
    }

    public function thenReturnTypeValueArray(): void
    {
        $this->assertInstanceOf(TypeValueArray::class, $this->areaYearTypeValue->getTypeValueArray());
    }
}
