<?php

namespace SIMBA3\Component\Domain\Value\Service;

use InvalidArgumentException;
use PHPUnit\Framework\TestCase;
use SIMBA3\Component\Domain\Filter\Service\AreasFilter;
use SIMBA3\Component\Domain\Filter\Service\YearsFilter;
use SIMBA3\Component\Domain\Value\Repository\AreaYearValueRepository;
use SIMBA3\Component\Domain\Value\Repository\YearValueRepository;

class FactoryTypeValueTest extends TestCase
{
    private FactoryTypeValue $factoryTypeValue;
    private AreaYearValueRepository $areaYearValueRepository;
    private YearValueRepository $yearValueRepository;
    private array $filters;
    private AreasFilter $areasFilter;
    private YearsFilter $yearsFilter;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->areaYearValueRepository = $this->createMock(AreaYearValueRepository::class);
        $this->yearValueRepository = $this->createMock(YearValueRepository::class);
        $this->areasFilter = $this->createMock(AreasFilter::class);
        $this->yearsFilter = $this->createMock(YearsFilter::class);
        $this->filters = array("areasFilter" => $this->areasFilter, "yearsFilter" => $this->yearsFilter);
    }

    /** @test */
    public function shouldFactoryTypeValueExpectsErrorWhenNotExistsTheType(): void
    {
        $this->givenAFactoryTypeValue();
        $this->thenExpectsInvalidArgumentException();
        $this->whenGetObjectTypeValueNotExists();
    }

    /** @test */
    public function shouldFactoryTypeValueReturnAreaYearTypeValue(): void
    {
        $this->givenAFactoryTypeValue();
        $this->whenGetObjectTypeValueIsAreaYearValueThenReturnAreaYearTypeValue();
    }

    /** @test */
    public function shouldFactoryTypeValueReturnYearTypeValue(): void
    {
        $this->givenAFactoryTypeValue();
        $this->whenGetObjectTypeValueIsYearValueThenReturnYearTypeValue();
    }

    private function givenAFactoryTypeValue(): void
    {
        $this->factoryTypeValue = new FactoryTypeValue(
            $this->areaYearValueRepository,
            $this->yearValueRepository
        );
    }

    private function thenExpectsInvalidArgumentException(): void
    {
        $this->expectException(InvalidArgumentException::class);
    }

    private function whenGetObjectTypeValueNotExists(): void
    {
        $this->factoryTypeValue->getObjectTypeValue("NOT EXISTS", 1001, $this->filters);
    }

    private function whenGetObjectTypeValueIsAreaYearValueThenReturnAreaYearTypeValue(): void
    {
        $this->assertInstanceOf(
            AreaYearTypeValue::class,
            $this->factoryTypeValue->getObjectTypeValue("AREA_YEAR_VALUE", 1001, $this->filters)
        );
    }

    private function whenGetObjectTypeValueIsYearValueThenReturnYearTypeValue(): void
    {
        $this->assertInstanceOf(
            YearTypeValue::class,
            $this->factoryTypeValue->getObjectTypeValue("YEAR_VALUE", 1001, $this->filters)
        );
    }
}
